### ISSUE TITLE
Portrait & landscape view on the run time

### ISSUE THREAD

**Issue by nuhil** [calonso/ios-arkit#2]
The engine starts using either portrait view or landscape view configuration from taking rotation/orientation status of the main view controller. So, if I Start AR with portrait view & then rotate the device to landscape, then it does not start listening based on landscape configuration. 
It would be great if the engine restarts/listens while changing device orientation/rotation (portrait to landscape to portrait) on the run time.

**Comment by calonso** [comment]
You're right about it, it would be great, but I don't think is something straightforward to implement. Maybe you're up for it? I'd be happy to help.

PS: Sorry for being so slow at responding. It completely went under the radar.

**Comment by calonso** [comment]
Closing as inactive, please reopen it if you need further help
