### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by Sneakr** [calonso/ios-arkit#4]
Hello, 

First I want to thank you for good project! I am a fairly beginner, and my question is, do you have any good guidance/solution for overlapping objects behind eachother? For example, maybe put then above or generate a list or something?

Thank you for any advice and support!

**Comment by calonso** [comment]
Hi there... IIRC they're overlapped based on proximity, so the closest is first in the line. On the other hand I see your point but I have nothing in mind, maybe you feel like adding something to the engine? That would be great!!

On the other hand, glad you find the project useful!

**Comment by Sneakr** [comment]
Hi, thanks for response! I am trying to figure out something checking around the forums, I have just started coding in iOS , If I find anything useful or solution ill add it! cheers

**Comment by Sneakr** [comment]
Actually I managed to make a small fix to the radar view:

if (_points.count != _dotsView.subviews.count) {
            point = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"smAugmentedRealityDot"]];
            [_dotsView addSubview:point];
        }
        else {
            point = [_dotsView.subviews objectAtIndex:count];
        }

Instead of recreating and allocating new uiimageviews you just move position of existing one.

**Comment by calonso** [comment]
Can you open a pull request with your proposal along with some images on the final result?

Thanks!

**Comment by Sneakr** [comment]
I am a newbie at github and this was my first pull request. I hope I have done everything correctly ! It seems good tho I think :)

**Comment by calonso** [comment]
Great work @Sneakr. I've reviewed it and left a couple of minor comments.

Thank you very much!

**Comment by Sneakr** [comment]
Cool, Im glad I was of use, I commented on your changes how I was thinking when I set it up that way.  

Cheers
