### ISSUE TITLE
it doesn't take altitude into account?

### ISSUE THREAD

**Issue by sanjeevghimire** [calonso/ios-arkit#7]

**Comment by calonso** [comment]
It should. 

[Here](https://github.com/calonso/ios-arkit/blob/master/ARKit%20Example/Classes/ARKit/ARKitEngine.m#L363-L365) the object views are placed based on the inclination of the phone, may it be that you're not receiving heading updates?

Regards

**Comment by sanjeevghimire** [comment]
Thanks Alonso. I have a query regarding removing and addding geo coordinate from AR view because my geocoordinates long, lat, altitude cahnges over time. the problem i am having is its not removing the view, instead its stacking on top of the same view.

```let arGeoCoordinate: ARGeoCoordinate = ARGeoCoordinate(
            location: CLLocation.init(coordinate: flightAnnotation.coordinate, altitude: flightAnnotation.altitude, horizontalAccuracy: 0, verticalAccuracy: 0, course: flightAnnotation.heading , speed: flightAnnotation.speed, timestamp: NSDate(timeIntervalSinceNow: timeInterval) as Date))
        arGeoCoordinate.dataObject = flightAnnotation.title
        arGeoCoordinate.calibrate(usingOrigin: userLocation, useAltitude: true)
        
        if let annGeo = flightAnnotationsGeo[flightAnnotation.title!]{
            arKitEngine?.remove(annGeo)
        }
        arKitEngine?.add(arGeoCoordinate)
```

Can you help why its not remoing teh geo coordinates from ar view

**Comment by sanjeevghimire** [comment]
Thanks Alonso. Kudos to you on awesome customization to initial ARKit. 

one issue I have noticed is:
* when orientation is changed especially from portrait to landscape the it's not working.

is this a bug?

**Comment by calonso** [comment]
Orientation changes are currently not supported while in AR view. When the engine is started, [everything is computed based on the current orientation](https://github.com/calonso/ios-arkit/blob/master/ARKit%20Example/Classes/ARKit/ARKitEngine.m#L51-L82).

**Comment by calonso** [comment]
Closing as idle. Please reopen if necessary.
